### ISSUE TITLE
x86_64 assembly: Zero-terminated string

### ISSUE THREAD

**Issue by m1kal** [exercism/research_experiment_1#154]
The string that is passed to the function is zero-terminated, as in C.

An assembly programmer would expect string length to be passed in cx register.

README should be updated to avoid confusion.

**Comment by ErikSchierboom** [comment]
FYI @bergjohan

**Comment by bergjohan** [comment]
Thank you for the feedback!

There are many different conventions used when writing assembly, but because the tests are written in C, and run in a Linux Docker container, the convention here is defined by the System V ABI (https://www.uclibc.org/docs/psABI-x86_64.pdf), i.e. the first six integer arguments (from the left) are passed in `rdi`, `rsi`, `rdx`, `rcx`, `r8`, and `r9`, in that order. Additional integer arguments are passed on the stack.

The [README](https://github.com/exercism/research_experiment_1/blob/master/exercises/x86-64-assembly-1-a/README.md) states both that the string is null-terminated, and that it is passed in the `rdi` register:

> Your job is to define a function named `str_isalpha`, which takes a pointer to a null-terminated byte string

> The string is passed into the function via the `rdi` register

Could you explain in a little more detail what you think is missing from the README?

**Comment by m1kal** [comment]
Thanks for the explanation.

It seems I missed the "takes a pointer to a null-terminated byte string" when reading the instructions. I checked it twice, but I still missed it.
Sorry for the trouble, I'm closing the issue.

**Comment by iHiD** [comment]
Thanks everyone 🙂
